#!/bin/sh

set -e
set -u
set -o pipefail

# Similarly to what torsocks does with the --isolate option, we set a
# random username to make Tor use different circuits each time flatpak
# is called (see IsolateSOCKSAuth).
username=flatpak-$(head -c 12 /dev/urandom | xxd -p)
ALL_PROXY="socks5h://${username}:0@127.0.0.1:9050"
export ALL_PROXY

exec /usr/bin/flatpak.real "${@}"
