#!/usr/bin/python3 -I

from pathlib import Path

import gi

gi.require_version("Gio", "2.0")
gi.require_version("GLib", "2.0")
from gi.repository import Gio, GLib  # noqa: E402

PERSISTENT_DIR = Path("~/Persistent").expanduser()

secrets_settings = Gio.Settings(schema="org.gnome.World.Secrets")


def main():
    current_list = list(secrets_settings.get_value("last-opened-list"))

    for kdbx in PERSISTENT_DIR.glob("*.kdbx"):
        uri = f"file://{kdbx.absolute()}"
        if uri not in current_list:
            current_list.append(uri)

    secrets_settings.set_value("last-opened-list", GLib.Variant.new_strv(current_list))


if __name__ == "__main__":
    main()
