#!/usr/bin/python3 -I

import argparse
import json
import os
import pwd
import requests
import subprocess
import tempfile

from contextlib import contextmanager


MOAT_SERVICE_URL = "https://bridges.torproject.org/moat"
MOAT_SERVICE_SETTINGS_URL = f"{MOAT_SERVICE_URL}/circumvention/settings"
MOAT_SERVICE_DEFAULTS_URL = f"{MOAT_SERVICE_URL}/circumvention/defaults"
MOAT_FRONT = "vuejs.org"
MOAT_REFLECTOR = "https://bespoke-strudel-c243cc.netlify.app"


def meek_credentials():
    # We escape \=; as required by section 3.5 in
    # https://gitlab.torproject.org/tpo/core/torspec/-/blob/main/attic/text_formats/pt-spec.txt
    # but we also use percent-encoding for various special characters since these
    # credentials will be used in a URL (where e.g. : is used to separate user and
    # password, so if user contains a : there would otherwise be ambiguity which in our
    # case causes requests to raise an exception).
    def escape(s):
        replacers = {
            "\\": "\\\\",
            "=": "\\=",
            ";": "\\;",
            ":": "%3A",
            "/": "%2F",
        }
        for pattern, replacement in replacers.items():
            s = s.replace(pattern, replacement)
        return s

    s = f"url={escape(MOAT_REFLECTOR)};front={escape(MOAT_FRONT)}"
    if len(s) > 2 * 255:
        raise ValueError("the meek credentials don't fit into the SOCKS credentials")
    if len(s) <= 255:
        return (s, "\0")
    else:
        return (s[0:255], s[255:])


@contextmanager
def meek_request(proxy=None):
    # This implements
    # https://gitlab.torproject.org/tpo/anti-censorship/team/-/wikis/Moat#using-lyrebird
    # and uses TorBrowser's implementation as a reference
    # https://gitlab.torproject.org/tpo/applications/tor-browser/-/blob/tor-browser-148.0a1-16.0-2/toolkit/modules/DomainFrontedRequests.sys.mjs?ref_type=heads#L159
    with tempfile.TemporaryDirectory() as tmpdir:
        env = os.environ.copy()
        env.update(
            {
                "TOR_PT_CLIENT_TRANSPORTS": "meek_lite",
                "TOR_PT_MANAGED_TRANSPORT_VER": "1",
                "TOR_PT_STATE_LOCATION": tmpdir,
            }
        )
        if proxy:
            env["TOR_PT_PROXY"] = proxy
        address = None
        p = None
        try:
            p = subprocess.Popen(
                ["/usr/bin/obfs4proxy"],
                env=env,
                stdout=subprocess.PIPE,
            )
            while True:
                line = p.stdout.readline()
                if not line:
                    raise RuntimeError("meek request failed")
                line = line.decode("utf-8").rstrip()
                if line.startswith("CMETHOD "):
                    _, pt, proto, _address = line.split()
                    if pt == "meek" or pt == "meek_lite":
                        if proto != "socks5":
                            raise NotImplementedError(
                                f"unsupported lyrebird CMETHOD listener protocol: {proto}"
                            )
                        address = _address
                elif line == "CMETHODS DONE":
                    if address is None:
                        raise RuntimeError("got no lyrebird CMETHOD address")
                    yield address
                    break
        finally:
            if p is not None:
                p.kill()


def fronted_fetch(meek_address, moat_address, region=None, transports=None):
    post_options = {}
    proxy_user, proxy_password = meek_credentials()
    post_options["proxies"] = {
        "https": f"socks5h://{proxy_user}:{proxy_password}@{meek_address}"
    }
    data = {}
    if region:
        data["country"] = region
    if transports:
        data["transports"] = transports
    if data:
        post_options["data"] = json.dumps(data)
    session = requests.Session()
    session.mount(moat_address, requests.adapters.HTTPAdapter(max_retries=2))
    response = session.post(moat_address, timeout=10, **post_options)
    return json.loads(response.content)


def get_settings(fallback=False, proxy=None, region=None, transports=None):
    def fronted_get_settings(meek_address):
        return fronted_fetch(
            meek_address,
            MOAT_SERVICE_SETTINGS_URL,
            region=region,
            transports=transports,
        )

    def fronted_get_defaults(meek_address):
        return fronted_fetch(
            meek_address, MOAT_SERVICE_DEFAULTS_URL, transports=transports
        )

    with meek_request(proxy=proxy) as meek_address:
        response = fronted_get_settings(meek_address)
        if fallback and not response.get("settings", []):
            response = fronted_get_defaults(meek_address)
    return response


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--proxy", metavar="PROXY", dest="proxy")
    p.add_argument("--region", metavar="CODE", dest="region")
    p.add_argument("--defaults-fallback", action="store_true", dest="fallback")
    p.add_argument(
        "--transport", metavar="TRANSPORT", action="append", dest="transports"
    )
    args = p.parse_args()
    try:
        print(
            json.dumps(
                get_settings(
                    fallback=args.fallback,
                    proxy=args.proxy,
                    region=args.region,
                    transports=args.transports,
                )
            )
        )
    except requests.RequestException as e:
        print(json.dumps({"requests-error": f"{type(e).__name__}: {e}"}))
