#!/usr/bin/python3 -I

import gettext
import psutil
import subprocess
import sys

import gi

from gi.repository import GLib

gi.require_version("Notify", "0.7")
from gi.repository import Notify  # NOQA: E402

DONT_ASK_IDENTIFIER = "low-ram-notify-user"


gettext.install("tails")
_ = gettext.gettext


class LowRamNotifier:
    def __init__(self, show_suppress_button=False):
        self.title = _("Insufficient Memory Detected")
        self.body = _(
            "Tails requires 3 GB of RAM. "
            "You might experience reduced performance, instability, or crashes."
        )

        Notify.init("org.boum.tails.low-ram-notify-user")
        # We need to hold a reference to the notification until the callbacks
        # are called. That's why we use an instance variable.
        self.notification = Notify.Notification.new(self.title, self.body)
        self.notification.set_hint("transient", GLib.Variant("u", 1))
        self.notification.set_timeout(0)
        if show_suppress_button:
            self.notification.add_action(
                "hide", _("Don't Show Again"), self.cb_notification_clicked
            )
        self.notification.add_action(
            "documentation", _("Learn More"), self.cb_notification_clicked
        )
        self.notification.connect("closed", lambda *x: sys.exit(0))

        self.notification.show()

    def cb_notification_clicked(self, notification, action, user_data=None):
        if action == "hide":
            subprocess.run(
                [
                    "/usr/local/bin/tails-ask-again",
                    "--dont-ask-again",
                    DONT_ASK_IDENTIFIER,
                ],
                check=False,
            )
        elif action == "documentation":
            subprocess.run(
                [
                    "/usr/local/lib/run-with-user-env",
                    "tails-documentation",
                    "doc/about/requirements",
                ],
                check=False,
            )
        sys.exit(0)


if __name__ == "__main__":
    required_ram = 3 * 2**30
    if required_ram < psutil.virtual_memory().total:
        sys.exit(0)
    dont_ask_status = (
        subprocess.check_output(
            ["/usr/local/bin/tails-ask-again", "--timeout", "30", DONT_ASK_IDENTIFIER]
        )
        .decode()
        .strip()
    )
    if dont_ask_status == "hide":
        sys.exit(0)

    mainloop = GLib.MainLoop.new(None, False)
    LowRamNotifier(show_suppress_button=(dont_ask_status != "unavailable"))
    mainloop.run()
