#!/usr/bin/python3 -I
"""
Detects if action is needed to keep using Tails on current hardware.

The output is guaranteed to be valid JSON, and will be an object with these fields:

- action_needed: a boolean. always present.
- os: a list of string.
"""

import enum
import logging
import os
import subprocess
import sys

from tailslib.uefi_ca import Detection

log = logging.getLogger("tails-uefi-ca-detect")


class UefiState(enum.Enum):
    SECURE_BOOT_DISABLED = 1
    GOOD = 2
    BAD = 3


def detect_uefi_ca() -> UefiState:
    try:
        output = subprocess.check_output(
            ["/usr/bin/mokutil", "--kek", "--short"],
            text=True,
        )
    except subprocess.CalledProcessError:
        log.exception("Error invoking mokutil")
        return UefiState.SECURE_BOOT_DISABLED
    else:
        return parse_uefi_ca(output)


def parse_uefi_ca(output: str) -> UefiState:
    """
    >>> parse_uefi_ca("\\n\\n").name
    'SECURE_BOOT_DISABLED'
    >>> old = "3590bfd89 Microsoft Corporation KEK CA 2011\\n"
    >>> new = "xxxxxxxxx Microsoft Corporation KEK 2K CA 2023\\n"
    >>> parse_uefi_ca(old).name
    'BAD'
    >>> parse_uefi_ca(old + new).name
    'GOOD'
    """
    if not output.strip():
        return UefiState.SECURE_BOOT_DISABLED
    if any(
        "Microsoft Corporation KEK 2K CA 2023" in line for line in output.split("\n")
    ):
        return UefiState.GOOD
    return UefiState.BAD


def os_probe() -> list[str]:
    """
    Returns a list of relevant operating systems on this computer.

    Our current definition of relevant is: Windows-only
    """
    try:
        output = subprocess.check_output(
            ["/usr/bin/os-prober"],
            text=True,
        )
    except subprocess.CalledProcessError:
        log.exception("Error invoking os-prober")
        return []
    return parse_os_probe(output)


def parse_os_probe(output) -> list[str]:
    """
    >>> parse_os_probe("")
    []
    >>> parse_os_probe("\\n\\nmalformed\\n")
    []
    >>> parse_os_probe("/dev/sda1:Linux:Linux:efi")
    []
    >>> win = ( \
            "/dev/nvme0n1p2@/EFI/Microsoft/Boot/bootmgfw.efi:" \
            "Windows Boot Manager:Windows:efi" \
            )
    >>> parse_os_probe(win)
    ['Windows Boot Manager']
    """
    ret = []
    for line in output.split("\n"):
        info = line.strip().split(":")
        try:
            category = info[2]
            detail = info[1]
        except IndexError:  # empty line or malformed line
            continue
        if category == "Windows":
            ret.append(detail)

    return ret


def output(d: Detection):
    print(d.model_dump_json())


def no_action_needed() -> int:
    d = Detection(action_needed=False, os=[])
    output(d)
    return 0


def main() -> int:
    if sys.argv[1:] == ["--doctest"]:
        import doctest

        ret = doctest.testmod(verbose=False)
        print(sys.argv[0], "doctest:", ret)
        return 1 if ret.failed else 0

    if os.getuid() != 0:
        print(f"{sys.argv[0]} must be run as root", file=sys.stderr)
        sys.exit(1)

    uefi_state = detect_uefi_ca()
    if uefi_state != UefiState.BAD:
        return no_action_needed()

    available_os = os_probe()
    if not available_os:
        return no_action_needed()

    output(Detection(action_needed=True, os=available_os))
    return 0


if __name__ == "__main__":
    sys.exit(main())
