#!/usr/bin/python3 -I

import gettext
import logging

import additional_software
from additional_software import (
    add_additional_packages,
    get_additional_packages,
    notify,
)

from tailslib.locale import apply_selected_locale
from tailslib.migration import Migration
from tailslib.persistence import (
    additional_software_persistence_feature_is_active,
    thunderbird_persistence_feature_is_active,
)
from tailslib.thunderbird import (
    thunderbird_l10n_package,
)

apply_selected_locale()
gettext.textdomain("tails")
_ = gettext.gettext


def handle_thunderbird_migration():
    migration = Migration("21375-thunderbird-iteration-1")

    if migration.succeeded:
        logging.info(
            "Migration 21375-thunderbird-iteration-1 has already succeeded "
            "⇒ no migration needed",
        )
        return

    if migration.not_needed:
        logging.info(
            "Migration 21375-thunderbird-iteration-1 was previously identified "
            "as not needed ⇒ skipping"
        )
        return

    if not thunderbird_persistence_feature_is_active():
        logging.info(
            "Thunderbird persistent storage feature is not enabled "
            "⇒ no migration needed",
        )
        # We don't record "migration.not_needed = True" here because
        # we want to apply the migration if the user later enables
        # the Thunderbird persistent storage feature.
        return

    if additional_software_persistence_feature_is_active():
        if "thunderbird" in get_additional_packages():
            # The user added thunderbird to Additional Software
            # themselves already, so we avoid applying the migration:
            # it would be a harmless no-op, except it would record
            # that we applied the migration successfully, and then the
            # thunderbird wrapper would tell the user about it, which
            # makes no sense.
            logging.info(
                "Thunderbird is already in Additional Software "
                "⇒ no migration needed",
            )
            migration.not_needed = True
            return

        logging.info("Adding Thunderbird to Additional Software")
        packages_to_add = {
            "thunderbird",
            # This list has to be kept in sync' with our list of
            # tier-1 languages:
            # https://tails.net/contribute/how/translate/#tier-1-languages
            "thunderbird-l10n-ar",
            "thunderbird-l10n-de",
            "thunderbird-l10n-es-es",
            "thunderbird-l10n-fr",
            "thunderbird-l10n-id",
            "thunderbird-l10n-it",
            "thunderbird-l10n-pt-br",
            "thunderbird-l10n-ru",
            "thunderbird-l10n-tr",
            "thunderbird-l10n-zh-cn",
        }
        l10n_package = thunderbird_l10n_package()
        if l10n_package is not None:
            logging.info("Found localization package: %s", l10n_package)
            packages_to_add |= {l10n_package}
        try:
            add_additional_packages(packages_to_add)
        except Exception:
            logging.exception("Failed to add additional packages")
            migration.succeeded = False
            notify(
                title=_("Thunderbird Migration"),
                body=_(
                    "We failed to add Thunderbird to your list of Additional Software.\n\nThunderbird will no longer be included by default in Tails 7.N+x (MONTH YEAR) and later."
                ),
                # TODO: UX
                documentation_target="anonymous_internet/thunderbird/migration/Debian/failure",
                urgent=True,
            )
            raise
        migration.succeeded = True
        # We don't notify here: instead we will let the user know if,
        # and when, they start Thunderbird.
    else:
        logging.info("Asking the user to add Thunderbird to Additional Software")
        # Here we intentionally don't record any state for the
        # migration: if the user does not add Thunderbird to their
        # Additional Software, we will ask them again, to minimize the
        # risk they miss these instructions.
        notify(
            title=_("Thunderbird Migration"),
            body=_(
                "You should add Thunderbird to your list of Additional Software.\n\nThunderbird will no longer be included by default in Tails 7.N+x (MONTH YEAR) and later."
            ),
            # TODO: UX
            documentation_target="anonymous_internet/thunderbird/migration/Debian/todo",
            urgent=True,
        )


def update_additional_software_configuration():
    logging.info("Starting the update of Additional Software configuration...")
    handle_thunderbird_migration()


def main():
    additional_software.set_up_logging()
    update_additional_software_configuration()


if __name__ == "__main__":
    main()
