#!/usr/bin/python3 -I

import gettext
import logging

import additional_software
from additional_software import (
    add_additional_packages,
    notify,
    notify_failure,
)

from tailslib.locale import apply_selected_locale
from tailslib.persistence import (
    additional_software_persistence_feature_is_active,
    thunderbird_persistence_feature_is_active,
)
from tailslib.thunderbird import (
    thunderbird_l10n_package,
)

apply_selected_locale()
gettext.textdomain("tails")
_ = gettext.gettext


def handle_thunderbird_migration():
    if not thunderbird_persistence_feature_is_active():
        logging.info(
            "Thunderbird persistent storage feature is not enabled "
            "⇒ no migration needed",
        )
        return

    if additional_software_persistence_feature_is_active():
        logging.info("Adding Thunderbird to Additional Software")
        packages_to_add = {
            "thunderbird",
            # This list has to be kept in sync' with our list of
            # tier-1 languages:
            # https://tails.net/contribute/how/translate/#tier-1-languages
            "thunderbird-l10n-ar",
            "thunderbird-l10n-de",
            "thunderbird-l10n-es-es",
            "thunderbird-l10n-fr",
            "thunderbird-l10n-id",
            "thunderbird-l10n-it",
            "thunderbird-l10n-pt-br",
            "thunderbird-l10n-ru",
            "thunderbird-l10n-tr",
            "thunderbird-l10n-zh-cn",
        }
        l10n_package = thunderbird_l10n_package()
        if l10n_package is not None:
            logging.info("Found localization package: %s", l10n_package)
            packages_to_add |= {l10n_package}
        try:
            add_additional_packages(packages_to_add)
        except Exception:
            logging.exception("Failed to add additional packages")
            notify_failure(
                _(
                    "TODO:UX "
                    "Failed to migrate Thunderbird configuration, "
                    "please report an error with WhisperBack.",
                ),
            )
            raise
        notify(
            title="TODO:UX Added Thunderbird to additional software",
            body="TODO:UX For your safety, Thunderbird will now be kept up-to-date from Debian.",
            # TODO: UX
            documentation_target="anonymous_internet/thunderbird/migration/Debian/done",
        )
    else:
        logging.info("Asking the user to add Thunderbird to Additional Software")
        notify(
            title="TODO:UX Please add Thunderbird to your additional software",
            body="TODO:UX",
            # TODO: UX
            documentation_target="anonymous_internet/thunderbird/migration/Debian/todo",
            urgent=True,
        )


def update_additional_software_configuration():
    logging.info("Starting the update of Additional Software configuration...")
    handle_thunderbird_migration()


def main():
    additional_software.set_up_logging()
    update_additional_software_configuration()


if __name__ == "__main__":
    main()
