---
distribution: trixie
ignore:
  temporary:
    open-ath9k-htc-firmware:
      version: "1.4.0-110-ge888634+dfsg1-0.3"
      reason: "Irrelevant changes, see #21409"
  general:
    - tor
    - live-boot
