---
distribution: trixie
ignore:
  temporary:
    PKG_NAME:
      version: "VERSION_STRING"
      reason: "see #XXXX"
    carl9170fw:
      version: "1.9.9-690-gc6e7ab0-0.1"
      reason: "The only change is a FTBFS fix (Debian#1123920)"
  general:
    - tor
    - live-boot
