#!/bin/sh

# Import ensure_hook_dependency_is_installed()
. /usr/local/lib/tails-shell-library/build.sh

ensure_hook_dependency_is_installed python3-jinja2 python3-pydantic

exec /usr/local/lib/generate-sudoers
