#!/bin/sh

set -e

echo "Make sure we install the required custom Tails packages"

# The following packages must be custom Tails versions: the tailsN
# suffix, N being a positive integer, is appended as-is to the version
# of the Debian package being forked, without any extra separator such
# as "." or "+".
TAILS_PACKAGES="
flatpak
"

OLD_VERSION_RE='([.]0|[+])tails[0-9]*$'
NEW_VERSION_RE='tails[0-9]+$'

package_version() {
    dpkg-query --show --showformat='${Version}' "${1}" 2>/dev/null
}

version_matches_new_re() {
    echo "$1" | grep --extended-regexp -q "$NEW_VERSION_RE"
}

version_matches_old_re() {
    echo "$1" | grep --extended-regexp -q "$OLD_VERSION_RE"
}

tails_package_installed() {
    version=$(package_version "${1}")
    if version_matches_old_re "$version"; then
        echo "Package '$1' uses an obsolete versioning scheme: '$version'." >&2
        exit 1
    fi
    version_matches_new_re "$version"
}

errors=
for p in ${TAILS_PACKAGES}; do
    if ! tails_package_installed "${p}"; then
        errors="${errors} ${p}"
    fi
done

if [ -n "${errors}" ]; then
    echo "These packages were expected to be custom Tails versions," \
        "but are not:" >&2
    for p in ${errors}; do
        echo " - ${p} ($(package_version "${p}"))" >&2
    done
    exit 1
fi
