# see wiki/src/contribute/design/greeter_storage.mdwn

[[commands]]
allowed_user = "Debian-gdm"
executable = "/usr/local/bin/tails-cleartext-storage"
args = ["load", "keymap"]

[[commands]]
allowed_user = "Debian-gdm"
executable = "/usr/local/bin/tails-cleartext-storage"
args = ["save", "keymap"]

