# Same purpose as config/chroot_local-includes/etc/sudoers.d/zzz_tps,
# see the comment there.
[[commands]]
user = "amnesia"
become = "tails-persistent-storage"
executable = "/usr/local/bin/tails-installer"
[commands.env_keep]
reason = "XXX"
value = ["ENVFILE"]

[[commands]]
user = "amnesia"
become = "tails-persistent-storage"
executable = "/usr/local/bin/tails-installer"
args = ["--backup"]
[commands.env_keep]
reason = "XXX"
value = ["ENVFILE"]

[[commands]]
user = "amnesia"
become = "tails-persistent-storage"
executable = "/usr/local/bin/tails-installer"
args = ["--verbose"]
[commands.env_keep]
reason = "XXX"
value = ["ENVFILE"]
