[[commands]]
env_keep = ["ENVFILE"]
reason = "run-tor-browser will validate arguments to reject options (see tails/tails#19595)"
executable = "/usr/local/lib/run-tor-browser"
arbitrary_arguments = true
user = "amnesia"
